### ISSUE TITLE
Installation with Laravel 5.5.45

### ISSUE THREAD

**Issue by mjstealth** [james2doyle/laravel-scout-sonic#1]
I have Laravel 5.5.45 and when I run  **"composer require james2doyle/laravel-scout-sonic"**, I get the following error. README seems to suggest that having 5.5.45 should be enough to install this plugin.

Any ideas?

` Problem 1

    - Installation request for james2doyle/laravel-scout-sonic ^1.0 -> satisfiable by james2doyle/laravel-scout-sonic[v1.0].
    - Conclusion: remove laravel/framework v5.5.45
    - Conclusion: don't install laravel/framework v5.5.45
    - james2doyle/laravel-scout-sonic v1.0 requires laravel/helpers ^1.0 -> satisfiable by laravel/helpers[v1.0.0, v1.0.1].
    - laravel/helpers v1.0.0 requires illuminate/support ~5.8.0 -> satisfiable by illuminate/support[v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.2, v5.8.3, v5.8.4, v5.8.8, v5.8.9].
    - laravel/helpers v1.0.1 requires illuminate/support ~5.8.0|~5.9.0 -> satisfiable by illuminate/support[v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.2, v5.8.3, v5.8.4, v5.8.8, v5.8.9].
    - don't install illuminate/support v5.8.0|don't install laravel/framework v5.5.45
    - don't install illuminate/support v5.8.11|don't install laravel/framework v5.5.45
    - don't install illuminate/support v5.8.12|don't install laravel/framework v5.5.45
    - don't install illuminate/support v5.8.14|don't install laravel/framework v5.5.45
    - don't install illuminate/support v5.8.15|don't install laravel/framework v5.5.45
    - don't install illuminate/support v5.8.17|don't install laravel/framework v5.5.45
    - don't install illuminate/support v5.8.18|don't install laravel/framework v5.5.45
    - don't install illuminate/support v5.8.2|don't install laravel/framework v5.5.45
    - don't install illuminate/support v5.8.3|don't install laravel/framework v5.5.45
    - don't install illuminate/support v5.8.4|don't install laravel/framework v5.5.45
    - don't install illuminate/support v5.8.8|don't install laravel/framework v5.5.45
    - don't install illuminate/support v5.8.9|don't install laravel/framework v5.5.45
    - Installation request for laravel/framework (locked at v5.5.45, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.45].
`

**Comment by james2doyle** [comment]
It's asking for illuminate/support ~5.8.0 which is a Laravel 5.8 package.

I wrote this for the latest version of scout. So you probably need to
upgrade Laravel to 5.8 before using this

**Comment by james2doyle** [comment]
@mjstealth any updates? if not I will close

**Comment by mjstealth** [comment]
Please go ahead and close. Thanks.
